version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

brews:
  - repository:
      owner: Quietscher
      name: homebrew-guppi
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/Quietscher/guppi"
    description: "TUI for managing multiple git repositories"
    license: "MIT"
    install: |
      bin.install "guppi"
    test: |
      system "#{bin}/guppi", "--version"
